### PR TITLE
New Aeson

### PR DESCRIPTION
**Pull request by cdupont**
This pull request allows the user to provide his own function for converting big numbers in conversions JSON -> BSON. Some defaults are provided: erroring, and bounding the number. I also provided some tests.
Building on @fujimura work.

### CODE REVIEW

**Comment by cdupont** [comment]
I committed better non-partial functions. @nh2 I think you can merge this version.

**Comment by nh2** [comment]
> I committed better non-partial functions. @nh2 I think you can merge this version.

@cdupont I found your original version better that passed you the `Scientific`, so that the user can inspect it in detail.

Are there any drawbacks to merging that one?

**Comment by cdupont** [comment]
@nh2 You can choose as you prefer. I found that just passing the Scientific was too "large" and led to partial functions:
```
bound :: Scientific -> BSON.Value
bound n | n< int64MinBound = Int64 minBound
bound n | n> int64MaxBound = Int64 maxBound
```
In that case, I would let the user define the entire conversion Scientific -> BSON.Value (not only invalid values). However, this leads to repetitions.

My last solution uses a Sum type: 
```
data OutOfBoundNumber = OutOfBoundMin S.Scientific
                      | OutOfBoundMax S.Scientific
```
Not perfect, but it simplifies/robustify a bit the code.

**Comment by cdupont** [comment]
Passing the Scientific directly is not bad actually. Some users might want to implement their own conversion function, for example encoding their Number over several BSON fields, who knows??

**Comment by cdupont** [comment]
OK I made a last version with passing directly the Scientific and some factorization.

**Comment by cdupont** [comment]
@nh2 is this OK?

**Comment by nh2** [comment]
Released as https://hackage.haskell.org/package/AesonBson-0.4.0

**Comment by nh2** [comment]
@cdupont @fujimura Thanks!

**Comment by cdupont** [comment]
Awesome, thanks!

**Pull request merged**
